# Generated by Django 4.2.11 on 2025-04-17 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='address',
            new_name='location',
        ),
    ]
