# Generated by Django 4.2.11 on 2025-04-17 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_rename_address_station_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='location',
            new_name='address',
        ),
    ]
