# Generated by Django 4.2.11 on 2025-04-01 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.TextField()),
                ('summary', models.CharField(max_length=20)),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('updaed_at', models.TimeField(auto_now=True)),
            ],
        ),
    ]
