# Generated by Django 4.2.20 on 2025-03-27 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='adult',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='pubdate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
