# Generated by Django 4.2.2 on 2025-03-27 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('pubdate', models.DateField(verbose_name='발행일자')),
                ('isbn', models.IntegerField(verbose_name='10자리isbn')),
                ('author', models.CharField(max_length=100, verbose_name='작가')),
                ('link', models.URLField(verbose_name='상품링크')),
                ('description', models.TextField(verbose_name='책설명')),
                ('publisher', models.CharField(max_length=100, verbose_name='출판사')),
                ('adult', models.BooleanField(verbose_name='성인')),
            ],
        ),
    ]
